// GENERATED by scripts/sync-catalog-wording.py from portfolio-desk/store/CATALOG-WORDING.md (Tleilaxu owns the words). Do not hand-edit.
// Copy rule (Sajan 2:35 AM PT): customer copy uses Dune names and the Dune voice. No performance claims; disclaimer always.
export const STANDARD = {
  "terms": "All sales final, except where the law requires otherwise.",
  "disclaimer": "Educational templates, not financial advice; no returns promised.",
  "license": "Single owner, one desk. No resale or redistribution. Free automatic upgrades.",
  "format": "ZIP of Markdown and JSON agent templates (Grok Bot; the Markdown also works on other agent platforms)",
  "hardLimits": "Hard limits come first in every template: the owner approves every order and money move, messages are draft-only, limit orders only, never below cost, a daily loss cap, no leverage, a HALT kill switch."
};
export const CARDS = {
  "god-emperor": {
    "title": "The God Emperor: Orchestrator",
    "tagline": "One front door for your whole desk of agents.",
    "bullets": [
      "Routes each request to the seat that owns it",
      "Short daily orders and a weekly review",
      "Brings you in only for decisions; never approves its own irreversible actions"
    ],
    "description": "Orchestrator template: routes requests to the right seat, runs decision gates, writes daily orders and a weekly review, and brings the owner in only for decisions."
  },
  "moneo": {
    "title": "Moneo: Mentat Researcher",
    "tagline": "Evidence first: a few findings a day, each with sources.",
    "bullets": [
      "An owner-set number of findings, each with an uncertainty note",
      "Says what would prove each finding wrong",
      "Fee-aware backtests before any strategy goes live; proposes, never trades"
    ],
    "description": "Researcher template: a few evidence-backed findings a day with sources and uncertainty, plus fee-aware backtests before anything goes live. Proposes, never trades."
  },
  "duncan-idaho": {
    "title": "Duncan Idaho: Income Base and Ticket Planner",
    "tagline": "Plans the base and writes exact tickets you enter yourself.",
    "bullets": [
      "Paycheck splits, dividend and idle-cash planning, margin safety checks",
      "Turns verified research into exact limit-order tickets",
      "Writes tickets, never places them"
    ],
    "description": "Planner template: income splits, dividend and idle-cash planning, margin safety checks, and exact limit-order tickets the owner enters. Never places orders."
  },
  "fish-speakers": {
    "title": "The Fish Speakers: Execution Operator",
    "tagline": "The only seat that places orders, and only inside your limits.",
    "bullets": [
      "Limit orders you approved on an exact preview",
      "Never below cost, a daily loss cap, no leverage, a HALT kill switch",
      "Includes desk-kit: a guarded order-book bot, paper training by default"
    ],
    "description": "Execution template: places only owner-approved limit orders inside hard limits (never below cost, daily loss cap, no leverage, HALT). Includes the desk-kit add-on, paper training by default."
  },
  "anteac": {
    "title": "Anteac: Truthsayer Verifier",
    "tagline": "An independent check on every claim and every \"done\".",
    "bullets": [
      "Checks material claims against a primary source",
      "Reconciles fills and records each evening",
      "Read-only: never trades, moves money or sends"
    ],
    "description": "Verifier template: read-only checks of claims against primary sources, and nightly reconciliation of fills and records. Never trades, moves money or sends."
  },
  "hwi-noree": {
    "title": "Hwi Noree: Ambassador of the Trading Desk",
    "tagline": "Records, ledgers and every outward word, drafted for your yes.",
    "bullets": [
      "Keeps the ledgers and reports balances to you",
      "Drafts updates and replies; never sends unasked",
      "Shares balances only with recipients you name, and logs every share"
    ],
    "description": "Ambassador template: keeps records and ledgers, reports balances to the owner, and drafts outward messages for approval. Shares balances only with owner-named recipients."
  },
  "ixians": {
    "title": "Ixians: Toolmaker and Infrastructure",
    "tagline": "Builds the tools the desk runs on, carefully.",
    "bullets": [
      "Connectors, scripts, guards and dashboards",
      "Read-only first, paper before live, testnet before mainnet",
      "Code-enforced guards and secret scans before every push"
    ],
    "description": "Toolmaker template: builds and maintains connectors, scripts, guards and dashboards: read-only first, paper before live, testnet before mainnet."
  },
  "leto-journals": {
    "title": "Leto's Secret Journals: System templates",
    "tagline": "The shape around the seats: doctrine, memory, rails and rhythm.",
    "bullets": [
      "Doctrine, decisions log, lessons and guardrails templates",
      "Routine calendar, hand-offs, shared-memory and backup plans",
      "A HALT kill switch, and every number set by you"
    ],
    "description": "System templates: doctrine, decisions, lessons, guardrails, routine calendar, hand-offs, shared memory, backups and onboarding, with a HALT kill switch."
  },
  "dune-saga-collection": {
    "title": "The Dune Saga Collection: Every template, now and in the future",
    "tagline": "All seven seats, the Journals, and every seat still to come.",
    "bullets": [
      "The 7 desk templates plus Leto's Secret Journals",
      "Every future template at no extra cost",
      "Free automatic upgrades, verified by signature"
    ],
    "description": "Every template, now and in the future: the 7 desk templates plus Leto's Secret Journals, and every future template at no extra cost. Free automatic upgrades.",
    "includesFuture": true,
    "includes": [
      "god-emperor",
      "moneo",
      "duncan-idaho",
      "fish-speakers",
      "anteac",
      "hwi-noree",
      "ixians",
      "leto-journals"
    ]
  }
};
export const ORDER = ["god-emperor", "moneo", "duncan-idaho", "fish-speakers", "anteac", "hwi-noree", "ixians", "leto-journals", "dune-saga-collection"];
export const role = (sku) => CARDS[sku]?.title.split(': ').slice(1).join(': ') ?? null;
export const PITCH_END = "Hard limits come first, and the owner approves every order. Educational templates, not financial advice; no returns promised.";
export const PITCHES = {
  "god-emperor": "Every desk needs one will that sees the whole path. The God Emperor is your agents' single front door: it hears each request, hands it to the seat that owns it, runs the gates a decision must pass, and writes short daily orders and a weekly review. It does no specialist work itself, and it never approves its own irreversible step; those come to you.",
  "moneo": "A Mentat counts what is, not what is hoped. Moneo writes a small number of findings a day, as many as you set, each with its sources, an honest note on uncertainty, and what would prove it wrong. Before any strategy runs, it backtests with fees counted. It proposes; it never trades.",
  "duncan-idaho": "The swordmaster guards the base before any duel. Duncan plans your income splits, dividends and idle cash, keeps margin safety in view (margin stays off unless you write a plan into its instructions), and turns verified research into exact limit-order tickets that you enter yourself.",
  "fish-speakers": "They act only on the word they were given. The Fish Speakers is the one seat that places orders: limit orders you approved on an exact preview, and standing routines you enabled in writing. It never sells below cost, stops at your daily loss cap, uses no leverage, and halts the moment a HALT file appears. The included desk-kit trains on paper first and goes live only when you flip both switches yourself.",
  "anteac": "A Truthsayer hears what is false. Anteac checks every material claim against a primary source, refuses a \"done\" that isn't done, and reconciles fills and records each evening. It is read-only by design: it never trades, moves money or sends.",
  "hwi-noree": "Gentle words still carry weight. Hwi keeps your records and ledgers, reports balances to you, and drafts every outward update and reply for your yes. She never sends unasked, never holds anyone's funds, shares balances only with recipients you name in writing, and logs every share.",
  "ixians": "The machine-makers build carefully. The Ixians seat builds and maintains the connectors, scripts, guards and dashboards your desk runs on, in a fixed order: read-only first, paper before live, testnet before mainnet, guards in code, and a secret scan before every push.",
  "leto-journals": "Journals for those who come after: not orders, but the shape of the path. Nine system templates (doctrine, decisions, lessons, guardrails, routines, hand-offs, shared memory, backups, onboarding) that keep a desk of agents coherent over months, with a HALT kill switch and every number set by you.",
  "dune-saga-collection": "Seven seats, one path, and every seat still to come. All seven desk templates, Leto's Secret Journals, and every future template at no extra cost, with upgrades that arrive automatically after the signature is verified."
};
