#!/usr/bin/env python3
"""Regenerate store-core/catalog-wording.js from portfolio-desk/store/CATALOG-WORDING.md (Tleilaxu owns the words)."""
import json, re, sys
SRC = sys.argv[1] if len(sys.argv) > 1 else '/home/box/agent-data/shared/portfolio-desk/store/CATALOG-WORDING.md'
OUT = 'store-core/catalog-wording.js'
t = open(SRC, encoding='utf-8').read()
NAMES = {'The God Emperor': 'god-emperor', 'Moneo': 'moneo', 'Duncan Idaho': 'duncan-idaho', 'The Fish Speakers': 'fish-speakers', 'Anteac': 'anteac',
         'Hwi Noree': 'hwi-noree', 'Ixians': 'ixians', "Leto's Secret Journals": 'leto-journals', 'The Dune Saga Collection': 'dune-saga-collection'}
def section(a, b): return t[t.index(a):t.index(b)]
std = {}
for k, key in [('Terms', 'terms'), ('Disclaimer', 'disclaimer'), ('License summary', 'license')]:
    std[key] = re.search(r'\*\*%s:\*\* "([^"]+)"' % k, t).group(1)
bj = json.loads(re.search(r'```json\n(.*?)```', section('## (b)', '## (c)'), re.S).group(1))
cards = {}
a = section('## (a)', '## (b)')
for block in re.split(r'\n(?=\*\*)', a):
    m = re.match(r'\*\*(.+?): (.+?)\*\*\n\*(.+?)\*\n((?:- .+\n?)+)', block)
    if not m: continue
    sku = NAMES[m.group(1)]
    cards[sku] = {'title': f'{m.group(1)}: {m.group(2)}', 'tagline': m.group(3), 'bullets': [l[2:].strip() for l in m.group(4).strip().split('\n')]}
for row in re.findall(r'^\| ([a-z-]+) \| [^|]+ \| \d+ \| (.+?) \|$', section('## (b)', '## (c)'), re.M):
    cards[row[0]]['description'] = row[1].strip()
coll = section('## (b)', '## (c)')
cards['dune-saga-collection'].update(includesFuture=True, includes=json.loads(re.search(r'"includes": (\[[^\]]+\])', coll).group(1)))
pitches = {}
c = section('## (c)', '## (d)')
end = re.search(r'Each pitch ends the same way: \*(.+?)\*', c).group(1)
for line in c.split('\n'):
    m = re.match(r'^\*\*(.+?)\.\*\* (.*)$', line)
    if m and m.group(1) in NAMES: pitches[NAMES[m.group(1)]] = re.sub(r'\s*\*Plain voice:.*$', '', m.group(2)).strip()
assert len(cards) == 9 and len(pitches) == 9 and all('description' in v for v in cards.values()), (cards.keys(), pitches.keys())
STANDARD = {**std, 'format': bj['format'], 'hardLimits': bj['hardLimits']}
order = ['god-emperor', 'moneo', 'duncan-idaho', 'fish-speakers', 'anteac', 'hwi-noree', 'ixians', 'leto-journals', 'dune-saga-collection']
js = f"""// GENERATED by scripts/sync-catalog-wording.py from portfolio-desk/store/CATALOG-WORDING.md (Tleilaxu owns the words). Do not hand-edit.
// Copy rule (Sajan 2:35 AM PT): customer copy uses Dune names and the Dune voice. No performance claims; disclaimer always.
export const STANDARD = {json.dumps(STANDARD, indent=2, ensure_ascii=False)};
export const CARDS = {json.dumps(cards, indent=2, ensure_ascii=False)};
export const ORDER = {json.dumps(order)};
export const role = (sku) => CARDS[sku]?.title.split(': ').slice(1).join(': ') ?? null;
export const PITCH_END = {json.dumps(end, ensure_ascii=False)};
export const PITCHES = {json.dumps(pitches, indent=2, ensure_ascii=False)};
"""
open(OUT, 'w', encoding='utf-8').write(js)
print('synced', OUT)
